version: "3"

# here we list our containers
services:

  api:
    # restart: always
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:14.5-alpine

volumes:
  postgres-db:
